source 'https://rubygems.org'

gem 'bootstrap-sass', '~> 3.3.6'
gem 'coffee-rails', '~> 4.1.0'
gem 'font-awesome-rails'
gem 'haml'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'money-rails'
gem 'rails-timeago'
gem 'rails', '4.2.5.1'
gem 'sass-rails', '~> 5.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'simple_form'
gem 'sqlite3'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'

group :development, :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'fuubar'
  gem 'pry'
  gem 'rspec-its'
  gem 'rspec-rails'
  gem 'rspec'
  gem 'shoulda'
end

group :development do
  gem 'spring'
end
